org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

# 沙箱代理（仅本环境需要，正式构建机应删除）
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=18080
systemProp.http.nonProxyHosts=localhost|127.0.0.1|*.svc|.cluster.local
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=18080
systemProp.https.nonProxyHosts=localhost|127.0.0.1|*.svc|.cluster.local
